import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { PublicFooter, PublicHeader } from "@/components/PublicChrome";
import PageMeta from "@/components/PageMeta";

const people = [{slug:"instructor-a",name:"AI Agent 설계",role:"AI Agent / Strategy",intro:"복잡한 업무를 실행 가능한 시스템으로 번역합니다.",bio:"업무의 맥락을 구조화하고, 사람의 판단과 자동화가 만나는 지점을 설계합니다.",credentials:["AI Agent 설계 워크숍","업무 자동화 컨설팅","프로젝트 코호트 멘토"],tracks:["AI Agent Builder","기업 맞춤 과정"]},{slug:"instructor-b",name:"콘텐츠 시스템",role:"Content / Editorial",intro:"브랜드의 언어를 반복 가능한 생산 흐름으로 만듭니다.",bio:"좋은 콘텐츠가 한 번의 영감이 아니라 운영 가능한 시스템이 되도록 돕습니다.",credentials:["콘텐츠 시스템 설계","브랜드 컨텍스트 구축","멀티채널 운영"],tracks:["Content Automation"]},{slug:"instructor-c",name:"마케팅 운영",role:"Marketing / Growth",intro:"데이터와 메시지를 연결해 운영 가능한 캠페인을 설계합니다.",bio:"캠페인 브리프부터 리드 후속 조치와 성과 리포트까지 이어지는 흐름을 만듭니다.",credentials:["마케팅 자동화","리드 운영 워크플로","성과 대시보드 설계"],tracks:["Marketing Automation","기업 맞춤 과정"]}];

export default function Instructors(){ const [,params]=useRoute("/instructors/:slug"); const live=trpc.content.public.useQuery(); const source=live.data?.instructors?.length ? live.data.instructors.map(r=>({...r, credentials:r.credentials.split("\\n"), tracks:r.tracks.split("\\n") })) : people; const person=params?source.find(p=>p.slug===params.slug):null; if(person) return <Profile person={person}/>; return <div><PageMeta title="Agentro 강사진 — 현업 언어로 시스템을 만드는 사람들" description="각자의 현업 언어로 업무를 시스템으로 바꾸는 Agentro 강사진을 소개합니다." image="/manus-storage/agentro-og-instructor_fab88e98.svg" type="profile" /><PublicHeader /><section className="subnav"><div className="container"><div className="eyebrow">04 / instructors</div><h1>강사진</h1><p>각자의 현업 언어로 업무를 시스템으로 바꾸는 사람들을 소개합니다.</p></div></section><section className="section"><div className="container grid3">{source.map(p=><Link href={`/instructors/${p.slug}`} className="card instructor-card" key={p.slug}><div className="avatar">{p.name.slice(-1)}</div><span className="eyebrow">{p.role}</span><h3>{p.name}</h3><p>{p.intro}</p><div className="chips">{p.tracks.map(t=><span className="chip" key={t}>{t}</span>)}</div><div className="card-meta"><span>VIEW PROFILE</span><span>↗</span></div></Link>)}</div></section><PublicFooter /></div> }

function Profile({person}:{person:typeof people[number]}){return <div><PageMeta title={`${person.name} — Agentro 강사 프로필`} description={`${person.intro} Agentro의 실무형 교육과 커리큘럼을 확인하세요.`} image="/manus-storage/agentro-og-instructor_fab88e98.svg" type="profile" /><PublicHeader /><main className="container profile-page"><Link href="/instructors" className="eyebrow">← INSTRUCTORS</Link><section className="profile-hero" style={{marginTop:35}}><div className="profile-photo">{person.name.slice(-1)}</div><div><div className="role">{person.role}</div><h1>{person.name}</h1><p style={{fontSize:19,maxWidth:680,color:"var(--ink-2)"}}>{person.intro}</p><div className="chips" style={{marginTop:22}}>{person.tracks.map(t=><span className="chip" key={t}>{t}</span>)}</div></div></section><section className="profile-columns"><div><h3>About</h3><p style={{color:"var(--ink-2)",fontSize:16}}>{person.bio}</p><h3 style={{marginTop:48}}>Credentials</h3><ul className="profile-list">{person.credentials.map((c,i)=><li key={c}><strong>0{i+1} / {c}</strong><span>검증 및 공개 동의 상태를 확인한 프로필 콘텐츠입니다.</span></li>)}</ul></div><div><h3>Curriculum</h3><ul className="profile-list">{["업무 맥락을 구조화하는 법","판단 기준과 프롬프트 설계","도구 연결과 예외 처리","사람이 검수하는 운영 구조"].map((c,i)=><li key={c}><strong>Step {String(i+1).padStart(2,"0")} — {c}</strong><span>실습·피드백·적용 과정을 통해 내 업무에 연결합니다.</span></li>)}</ul><Link href="/programs" className="btn primary" style={{marginTop:32}}>담당 프로그램 보기 ↗</Link></div></section></main><PublicFooter /></div>}
